;-------------------;
;  PIN DEFINITIONS  ;
;-------------------;
.EQU	RED_LED_DDR = DDRB
.EQU	RED_LED_PORT = PORTB
.EQU	RED_LED = PINB4

.EQU	GREEN_LED_DDR = DDRB
.EQU	GREEN_LED_PORT = PORTB
.EQU	GREEN_LED = PINB3

.EQU	STRAIN_GAUGE_DDR = DDRA
.EQU	STRAIN_GAUGE_PIN = PINA
.EQU	STRAIN_GAUGE_PORT = PORTA
.EQU	STRAIN_GAUGE = PINA0

.EQU	FINISH_LINE_DDR = DDRD
.EQU	FINISH_LINE_PIN = PIND
.EQU	FINISH_LINE_PORT = PORTD
.EQU	FINISH_LINE = PIND2

.EQU	DISTANCE_DDR = DDRD
.EQU	DISTANCE_PIN = PIND
.EQU	DISTANCE_PORT = PORTD
.EQU	 DISTANCE = PIND3

.EQU	MOTOR_DDR = DDRD
.EQU	MOTOR_PIN = PIND
.EQU	MOTOR_PORT = PORTD
.EQU	MOTOR = PIND7
