;-------------------;
;  PIN DEFINITIONS  ;
;-------------------;
; Red LED
.EQU	RED_LED_DDR = DDRB
.EQU	RED_LED_PORT = PORTB
.EQU	RED_LED = PINB4

; Green LED
.EQU	GREEN_LED_DDR = DDRB
.EQU	GREEN_LED_PORT = PORTB
.EQU	GREEN_LED = PINB3

; Strain gauge / turn sensor
.EQU	STRAIN_GAUGE_DDR = DDRA
.EQU	STRAIN_GAUGE_PIN = PINA
.EQU	STRAIN_GAUGE_PORT = PORTA
.EQU	STRAIN_GAUGE = PINA0

; Finish line sensor
.EQU	FINISH_LINE_DDR = DDRD
.EQU	FINISH_LINE_PIN = PIND
.EQU	FINISH_LINE_PORT = PORTD
.EQU	FINISH_LINE = PIND2

; Motor revolution / distance sensor
.EQU	DISTANCE_DDR = DDRD
.EQU	DISTANCE_PIN = PIND
.EQU	DISTANCE_PORT = PORTD
.EQU	DISTANCE = PIND3

; Motor PWM output
.EQU	MOTOR_DDR = DDRD
.EQU	MOTOR_PIN = PIND
.EQU	MOTOR_PORT = PORTD
.EQU	MOTOR = PIND7
